In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("StudentMentalhealth.csv")

print("Linhas e colunas:", df.shape)
df.head()

Linhas e colunas: (101, 11)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    str
 1   Choose your gender                            101 non-null    str
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    str
 4   Your current year of Study                    101 non-null    str
 5   What is your CGPA?                            101 non-null    str
 6   Marital status                                101 non-null    str
 7   Do you have Depression?                       101 non-null    str
 8   Do you have Anxiety?                          101 non-null    str
 9   Do you have Panic attack?                     101 non-null    str
 10  Did you seek any specialist for a treatment?  101 non-null    str
dtypes: float64(1), str(10)
memory usage: 8.8 KB

In [6]:
df["Age"].describe()

count    100.00000
mean      20.53000
std        2.49628
min       18.00000
25%       18.00000
50%       19.00000
75%       23.00000
max       24.00000
Name: Age, dtype: float64

In [7]:
df.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [9]:
df["Age"].value_counts()

Age
18.0    32
24.0    23
19.0    21
23.0    13
20.0     6
21.0     3
22.0     2
Name: count, dtype: int64

In [13]:
df["Marital status"].value_counts()

Marital status
No     85
Yes    16
Name: count, dtype: int64

In [14]:
print("Antes:", df.shape)

df = df.drop_duplicates()

print("Depois:", df.shape)

Antes: (101, 11)
Depois: (101, 11)

In [15]:
df = df.dropna()

In [16]:
df.isnull().sum().sum()

np.int64(0)

In [17]:
df.dtypes

Timestamp                                           str
Choose your gender                                  str
Age                                             float64
What is your course?                                str
Your current year of Study                          str
What is your CGPA?                                  str
Marital status                                      str
Do you have Depression?                             str
Do you have Anxiety?                                str
Do you have Panic attack?                           str
Did you seek any specialist for a treatment?        str
dtype: object

In [18]:
print(df.shape)

df.head()

(100, 11)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No